module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container": "#f0edef",
        "on-surface": "#1b1b1d",
        "error": "#ba1a1a",
        "tertiary-container": "#271901",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#98805d",
        "primary-container": "#131b2e",
        "on-error": "#ffffff",
        "surface-tint": "#565e74",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface": "#fcf8fa",
        "surface-container-low": "#f6f3f5",
        "surface-container-highest": "#e4e2e4",
        "on-tertiary-fixed-variant": "#574425",
        "secondary-fixed-dim": "#b7c8e1",
        "primary": "#000000",
        "surface-bright": "#fcf8fa",
        "on-surface-variant": "#45464d",
        "on-primary": "#ffffff",
        "on-primary-container": "#7c839b",
        "on-primary-fixed": "#131b2e",
        "background": "#fcf8fa",
        "on-tertiary-fixed": "#271901",
        "on-secondary-fixed": "#0b1c30",
        "inverse-on-surface": "#f3f0f2",
        "on-background": "#1b1b1d",
        "surface-container-high": "#eae7e9",
        "secondary": "#505f76",
        "secondary-fixed": "#d3e4fe",
        "surface-variant": "#e4e2e4",
        "on-secondary-container": "#54647a",
        "tertiary-fixed": "#fcdeb5",
        "surface-dim": "#dcd9db",
        "outline": "#76777d",
        "secondary-container": "#d0e1fb",
        "inverse-surface": "#303032",
        "primary-fixed": "#dae2fd",
        "inverse-primary": "#bec6e0",
        "tertiary-fixed-dim": "#dec29a",
        "primary-fixed-dim": "#bec6e0",
        "outline-variant": "#c6c6cd",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary": "#000000",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "warning-container": "#fef08a",
        "on-warning-container": "#854d0e",
        "warning": "#ca8a04"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "container-max": "1280px",
        "xl": "40px",
        "sm": "8px",
        "md": "16px",
        "base": "8px",
        "xs": "4px",
        "lg": "24px",
        "gutter": "24px"
      },
      "fontFamily": {
        "label-sm": ["Public Sans"],
        "body-lg": ["Public Sans"],
        "headline-md": ["Public Sans"],
        "body-md": ["Public Sans"],
        "label-md": ["Public Sans"],
        "display-sm": ["Public Sans"],
        "numeric-data": ["Public Sans"],
        "display-lg": ["Public Sans"]
      },
      "fontSize": {
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "display-sm": ["30px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "numeric-data": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
